import { defineItems } from "@/content/authoring";

/** Canonical built-in RPG item seed shared by runtime fallback and the authoring pack. */
export const DEFAULT_RPG_ITEMS = defineItems({
  stone: {
    id: "stone",
    name: "Stone",
    category: "mineral",
    rarity: "common",
    trait1: "Density",
    trait2: "None",
    sources: ["gather"],
    description: "Common grey stone. The foundation of everything and the value of nothing.",
  },
  stone_block: {
    id: "stone_block",
    name: "Stone Block",
    category: "component",
    rarity: "common",
    trait1: "Density",
    trait2: "None",
    sources: ["craft"],
    description: "Squared stone fit for walls, roads, and other stubborn things.",
  },
  copper_ore: {
    id: "copper_ore",
    name: "Copper Ore",
    category: "mineral",
    rarity: "common",
    trait1: "Density",
    trait2: "None",
    sources: ["gather"],
    description: "Dull green-brown ore. The Accord mints its coins from this. Ironic.",
  },
  iron_ore: {
    id: "iron_ore",
    name: "Iron Ore",
    category: "mineral",
    rarity: "uncommon",
    trait1: "Density",
    trait2: "Sharpness",
    sources: ["gather"],
    description: "Deep-vein iron with crystalline grain structure. Cuts the hand that mines it.",
  },
  tin_ore: {
    id: "tin_ore",
    name: "Tin Ore",
    category: "mineral",
    rarity: "common",
    trait1: "Density",
    trait2: "None",
    sources: ["gather"],
    description: "Soft, malleable ore. Worthless alone. Essential in alloys.",
  },
  silver_ore: {
    id: "silver_ore",
    name: "Silver Ore",
    category: "mineral",
    rarity: "uncommon",
    trait1: "Density",
    trait2: "Magic",
    sources: ["gather"],
    description:
      "Pale ore that hums faintly under torchlight. Conducts essence better than copper.",
  },
  coal: {
    id: "coal",
    name: "Coal",
    category: "mineral",
    rarity: "common",
    trait1: "Density",
    trait2: "Toxicity",
    sources: ["gather"],
    description: "Burns hot and dirty. Every forge in every settlement runs on this.",
  },
  sulfur: {
    id: "sulfur",
    name: "Sulfur",
    category: "mineral",
    rarity: "uncommon",
    trait1: "Toxicity",
    trait2: "None",
    sources: ["gather", "expedition"],
    description: "Yellow crystalline powder. Stinks of rotten eggs. Essential for black powder.",
  },
  quartz: {
    id: "quartz",
    name: "Quartz",
    category: "mineral",
    rarity: "uncommon",
    trait1: "Magic",
    trait2: "None",
    sources: ["gather"],
    description: "Translucent crystal that refracts light into colors that shouldn't exist.",
  },
  obsidian_shard: {
    id: "obsidian_shard",
    name: "Obsidian Shard",
    category: "mineral",
    rarity: "rare",
    trait1: "Sharpness",
    trait2: "Density",
    sources: ["expedition"],
    description: "Volcanic glass. Fractures into edges sharper than any forged blade.",
  },
  ruby: {
    id: "ruby",
    name: "Ruby",
    category: "mineral",
    rarity: "rare",
    trait1: "Magic",
    trait2: "Density",
    sources: ["gather", "expedition"],
    description: "Deep crimson gemstone from the lowest mine shafts. Natural essence battery.",
  },
  sapphire: {
    id: "sapphire",
    name: "Sapphire",
    category: "mineral",
    rarity: "rare",
    trait1: "Magic",
    trait2: "Liquid",
    sources: ["expedition"],
    description:
      "Deep blue stone found near underground water sources. Resonates with liquid essence.",
  },
  raw_essence_crystal: {
    id: "raw_essence_crystal",
    name: "Raw Essence Crystal",
    category: "mineral",
    rarity: "legendary",
    trait1: "Magic",
    trait2: "Magic",
    sources: ["expedition"],
    description:
      "Crystallized pure essence. Warm to the touch. Looking at it too long causes headaches.",
  },
  oak_wood: {
    id: "oak_wood",
    name: "Oak Wood",
    category: "timber",
    rarity: "common",
    trait1: "Organic",
    trait2: "Density",
    sources: ["gather"],
    description: "Dense hardwood from the outer Whispering Woods. Still hums faintly when cut.",
  },
  spruce_wood: {
    id: "spruce_wood",
    name: "Spruce Wood",
    category: "timber",
    rarity: "common",
    trait1: "Organic",
    trait2: "None",
    sources: ["gather"],
    description: "Light, flexible softwood. Good for handles, arrows, and kindling.",
  },
  palm_wood: {
    id: "palm_wood",
    name: "Palm Wood",
    category: "timber",
    rarity: "uncommon",
    trait1: "Organic",
    trait2: "Liquid",
    sources: ["gather"],
    description: "Fibrous coastal timber. Retains moisture. Resistant to rot.",
  },
  pine_wood: {
    id: "pine_wood",
    name: "Pine Wood",
    category: "timber",
    rarity: "uncommon",
    trait1: "Organic",
    trait2: "None",
    sources: ["gather"],
    description: "Resinous northern wood. Burns slow and smells of turpentine.",
  },
  ironwood: {
    id: "ironwood",
    name: "Ironwood",
    category: "timber",
    rarity: "rare",
    trait1: "Organic",
    trait2: "Density",
    sources: ["expedition"],
    description:
      "Wood so dense it sinks in water. The deep-forest trees grow in essence-saturated soil.",
  },
  charcoal: {
    id: "charcoal",
    name: "Charcoal",
    category: "timber",
    rarity: "common",
    trait1: "Density",
    trait2: "Toxicity",
    sources: ["craft"],
    description: "Slow-burned wood. Hotter and cleaner than coal. Every alchemist keeps a supply.",
  },
  resin: {
    id: "resin",
    name: "Tree Resin",
    category: "timber",
    rarity: "common",
    trait1: "Organic",
    trait2: "Liquid",
    sources: ["gather"],
    description: "Amber sap that hardens on contact with air. Natural adhesive and sealant.",
  },
  rotted_wood: {
    id: "rotted_wood",
    name: "Rotted Wood",
    category: "timber",
    rarity: "common",
    trait1: "Organic",
    trait2: "Toxicity",
    sources: ["gather", "expedition"],
    description:
      "Decayed timber from deep forest floors. Crawling with fungal life. Handle carefully.",
  },
  red_herb: {
    id: "red_herb",
    name: "Red Herb",
    category: "herb",
    rarity: "uncommon",
    trait1: "Organic",
    trait2: "Magic",
    sources: ["gather", "expedition"],
    description: "Grows in essence-rich clearings. The base ingredient for most healing compounds.",
  },
  blue_moss: {
    id: "blue_moss",
    name: "Blue Moss",
    category: "herb",
    rarity: "uncommon",
    trait1: "Organic",
    trait2: "Liquid",
    sources: ["gather", "expedition"],
    description: "Bioluminescent cave moss. Thrives in wet, dark, essence-dense environments.",
  },
  nightshade: {
    id: "nightshade",
    name: "Nightshade",
    category: "herb",
    rarity: "rare",
    trait1: "Organic",
    trait2: "Toxicity",
    sources: ["expedition"],
    description: "Deadly purple berries. Everything about this plant wants to kill you.",
  },
  glowcap_mushroom: {
    id: "glowcap_mushroom",
    name: "Glowcap Mushroom",
    category: "herb",
    rarity: "uncommon",
    trait1: "Magic",
    trait2: "Organic",
    sources: ["expedition"],
    description: "Pale mushroom that emits soft light. Grows on essence-saturated deadwood.",
  },
  thornvine: {
    id: "thornvine",
    name: "Thornvine",
    category: "herb",
    rarity: "common",
    trait1: "Sharpness",
    trait2: "Organic",
    sources: ["gather"],
    description: "Barbed creeping vine. The thorns are essence-hardened to a razor edge.",
  },
  dried_tobacco: {
    id: "dried_tobacco",
    name: "Dried Tobacco",
    category: "herb",
    rarity: "common",
    trait1: "Organic",
    trait2: "Toxicity",
    sources: ["gather", "shop"],
    description: "Frontier luxury. Calms the nerves. Ruins the lungs. Everyone smokes it anyway.",
  },
  ghost_lily: {
    id: "ghost_lily",
    name: "Ghost Lily",
    category: "herb",
    rarity: "rare",
    trait1: "Magic",
    trait2: "Organic",
    sources: ["expedition"],
    description: "Translucent white flower found near Blight zones. Wilts within hours of picking.",
  },
  swamp_root: {
    id: "swamp_root",
    name: "Swamp Root",
    category: "herb",
    rarity: "uncommon",
    trait1: "Organic",
    trait2: "Toxicity",
    sources: ["gather", "expedition"],
    description: "Thick, gnarled root pulled from marshland. Bitter but medicinal when prepared.",
  },
  lavender: {
    id: "lavender",
    name: "Lavender",
    category: "herb",
    rarity: "common",
    trait1: "Organic",
    trait2: "Magic",
    sources: ["gather"],
    description: "Fragrant purple herb. One of the few pleasant things in Ashenmoor.",
  },
  bark_tea_leaves: {
    id: "bark_tea_leaves",
    name: "Bark Tea Leaves",
    category: "herb",
    rarity: "common",
    trait1: "Organic",
    trait2: "None",
    sources: ["gather"],
    description: "Stripped from the inner bark of young oaks. Makes a bitter, restorative tea.",
  },
  witchgrass: {
    id: "witchgrass",
    name: "Witchgrass",
    category: "herb",
    rarity: "uncommon",
    trait1: "Magic",
    trait2: "Toxicity",
    sources: ["expedition"],
    description: "Thin black grass that grows in perfect circles. Essence radiates from the roots.",
  },
  corpse_flower: {
    id: "corpse_flower",
    name: "Corpse Flower",
    category: "herb",
    rarity: "rare",
    trait1: "Toxicity",
    trait2: "Magic",
    sources: ["expedition"],
    description: "Blooms only on ground where something died. Smells exactly like its name.",
  },
  wolf_tooth: {
    id: "wolf_tooth",
    name: "Wolf Tooth",
    category: "animal",
    rarity: "uncommon",
    trait1: "Sharpness",
    trait2: "Organic",
    sources: ["expedition", "drop"],
    description:
      "Crystalline fang from a Whispering Woods predator. Sharper than it has any right to be.",
  },
  wolf_pelt: {
    id: "wolf_pelt",
    name: "Wolf Pelt",
    category: "animal",
    rarity: "uncommon",
    trait1: "Organic",
    trait2: "Density",
    sources: ["expedition", "drop"],
    description: "Thick, coarse fur. Insulates against cold and minor essence exposure.",
  },
  boar_tusk: {
    id: "boar_tusk",
    name: "Boar Tusk",
    category: "animal",
    rarity: "uncommon",
    trait1: "Sharpness",
    trait2: "Density",
    sources: ["expedition", "drop"],
    description: "Partially calcified tusk from a Stoneback Boar. Dense as horn, sharp as flint.",
  },
  boar_hide: {
    id: "boar_hide",
    name: "Boar Hide",
    category: "animal",
    rarity: "uncommon",
    trait1: "Density",
    trait2: "Organic",
    sources: ["expedition", "drop"],
    description: "Tough, stone-flecked hide. Natural armor that makes tanning a nightmare.",
  },
  veilmoth_wing: {
    id: "veilmoth_wing",
    name: "Veilmoth Wing",
    category: "animal",
    rarity: "rare",
    trait1: "Magic",
    trait2: "Organic",
    sources: ["expedition"],
    description: "Iridescent wing membrane. Dissolves in sunlight. Must be stored in darkness.",
  },
  cave_lurker_claw: {
    id: "cave_lurker_claw",
    name: "Cave Lurker Claw",
    category: "animal",
    rarity: "rare",
    trait1: "Sharpness",
    trait2: "Toxicity",
    sources: ["expedition", "drop"],
    description: "Retractable talon from the Deep Mine predators. Coated in a numbing secretion.",
  },
  rat_tail: {
    id: "rat_tail",
    name: "Rat Tail",
    category: "animal",
    rarity: "common",
    trait1: "Organic",
    trait2: "Toxicity",
    sources: ["expedition", "drop"],
    description:
      "From the oversized tunnel rats. Worth almost nothing. Alchemists buy them in bulk.",
  },
  crow_feather: {
    id: "crow_feather",
    name: "Crow Feather",
    category: "animal",
    rarity: "common",
    trait1: "Organic",
    trait2: "None",
    sources: ["gather"],
    description: "Iridescent black feather. Crows in Ashenmoor are larger than they should be.",
  },
  snake_venom_sac: {
    id: "snake_venom_sac",
    name: "Snake Venom Sac",
    category: "animal",
    rarity: "rare",
    trait1: "Toxicity",
    trait2: "Liquid",
    sources: ["expedition", "drop"],
    description:
      "Milky, translucent sac of concentrated venom. One puncture and you're dosing yourself.",
  },
  bone_fragment: {
    id: "bone_fragment",
    name: "Bone Fragment",
    category: "animal",
    rarity: "common",
    trait1: "Density",
    trait2: "Organic",
    sources: ["expedition", "drop"],
    description: "Splintered bone of uncertain origin. Could be animal. Could be older.",
  },
  sinew: {
    id: "sinew",
    name: "Sinew",
    category: "animal",
    rarity: "common",
    trait1: "Organic",
    trait2: "Density",
    sources: ["expedition", "drop"],
    description: "Dried tendon fiber. Stronger than rope when properly cured. Smells terrible.",
  },
  animal_fat: {
    id: "animal_fat",
    name: "Animal Fat",
    category: "animal",
    rarity: "common",
    trait1: "Organic",
    trait2: "Liquid",
    sources: ["expedition", "drop"],
    description: "Rendered tallow. Fuel for lamps, base for soaps, lubricant for mechanisms.",
  },
  spider_silk: {
    id: "spider_silk",
    name: "Spider Silk",
    category: "animal",
    rarity: "rare",
    trait1: "Organic",
    trait2: "Magic",
    sources: ["expedition"],
    description:
      "Harvested from the web-spinners of the deep forest. Stronger than steel by weight.",
  },
  demon_blood: {
    id: "demon_blood",
    name: "Demon Blood",
    category: "animal",
    rarity: "legendary",
    trait1: "Toxicity",
    trait2: "Liquid",
    sources: ["expedition"],
    description:
      "Black ichor from things that live below the deepest mines. Corrodes metal on contact.",
  },
  volatile_ash: {
    id: "volatile_ash",
    name: "Volatile Ash",
    category: "reagent",
    rarity: "common",
    trait1: "None",
    trait2: "None",
    sources: ["craft"],
    description: "The residue of a failed Crucible synthesis. Grey, inert, worthless. A reminder.",
  },
  essence_dust: {
    id: "essence_dust",
    name: "Essence Dust",
    category: "reagent",
    rarity: "uncommon",
    trait1: "Magic",
    trait2: "None",
    sources: ["craft", "expedition"],
    description: "Fine powder scraped from essence-rich surfaces. Mild arcane charge.",
  },
  grey_salt: {
    id: "grey_salt",
    name: "Grey Salt",
    category: "reagent",
    rarity: "uncommon",
    trait1: "Density",
    trait2: "Magic",
    sources: ["craft"],
    description: "Crystallized essence residue. Used to stabilize volatile alchemical reactions.",
  },
  black_powder: {
    id: "black_powder",
    name: "Black Powder",
    category: "reagent",
    rarity: "uncommon",
    trait1: "Toxicity",
    trait2: "Density",
    sources: ["craft"],
    description: "Explosive compound. Coal, sulfur, and careful handling. Or careless — once.",
  },
  quicksilver: {
    id: "quicksilver",
    name: "Quicksilver",
    category: "reagent",
    rarity: "rare",
    trait1: "Liquid",
    trait2: "Toxicity",
    sources: ["expedition", "craft"],
    description: "Liquid metal that pools in deep mine crevices. Fatally toxic if ingested.",
  },
  tallow: {
    id: "tallow",
    name: "Tallow",
    category: "reagent",
    rarity: "common",
    trait1: "Organic",
    trait2: "Liquid",
    sources: ["craft"],
    description: "Rendered animal fat, purified for alchemical use. Burns clean.",
  },
  phosphite_powder: {
    id: "phosphite_powder",
    name: "Phosphite Powder",
    category: "reagent",
    rarity: "uncommon",
    trait1: "Magic",
    trait2: "Toxicity",
    sources: ["craft"],
    description:
      "Glows faintly in the dark. Derived from cave minerals. Extremely irritating to skin.",
  },
  distilled_water: {
    id: "distilled_water",
    name: "Distilled Water",
    category: "reagent",
    rarity: "common",
    trait1: "Liquid",
    trait2: "None",
    sources: ["craft", "shop"],
    description: "Water boiled and condensed to remove essence contamination. Pure. Tasteless.",
  },
  acid_vial: {
    id: "acid_vial",
    name: "Acid Vial",
    category: "reagent",
    rarity: "rare",
    trait1: "Toxicity",
    trait2: "Liquid",
    sources: ["craft"],
    description:
      "Corrosive solution in a sealed glass container. Dissolves organic matter on contact.",
  },
  binding_agent: {
    id: "binding_agent",
    name: "Binding Agent",
    category: "reagent",
    rarity: "uncommon",
    trait1: "Density",
    trait2: "Liquid",
    sources: ["craft"],
    description: "Thick paste made from resin and mineral powder. Holds anything to anything else.",
  },
  bandage: {
    id: "bandage",
    name: "Linen Bandage",
    category: "medical",
    rarity: "common",
    trait1: "Organic",
    trait2: "None",
    sources: ["craft", "shop"],
    description: "Strips of clean cloth. Slows bleeding. Does not cure anything.",
  },
  healing_salve: {
    id: "healing_salve",
    name: "Healing Salve",
    category: "medical",
    rarity: "uncommon",
    trait1: "Organic",
    trait2: "Magic",
    sources: ["craft"],
    description: "Red Herb-based ointment. Accelerates wound closure. Standard Therapist stock.",
  },
  antidote: {
    id: "antidote",
    name: "Antidote",
    category: "medical",
    rarity: "uncommon",
    trait1: "Organic",
    trait2: "Toxicity",
    sources: ["craft"],
    description: "Neutralizes most common venoms and poisons. Tastes like chalk and regret.",
  },
  essence_ward: {
    id: "essence_ward",
    name: "Essence Ward",
    category: "medical",
    rarity: "rare",
    trait1: "Magic",
    trait2: "Density",
    sources: ["craft"],
    description:
      "Small stone tablet inscribed with stabilizing runes. Slows Greying while carried.",
  },
  ration: {
    id: "ration",
    name: "Trail Ration",
    category: "medical",
    rarity: "common",
    trait1: "Organic",
    trait2: "None",
    sources: ["shop", "craft"],
    description: "Dried meat, hardtack, and a pinch of salt. Keeps you moving. Barely.",
  },
  clean_water: {
    id: "clean_water",
    name: "Clean Water",
    category: "medical",
    rarity: "common",
    trait1: "Liquid",
    trait2: "None",
    sources: ["craft", "shop"],
    description: "Filtered and boiled. The single most valuable thing in the frontier.",
  },
  alcohol: {
    id: "alcohol",
    name: "Rotgut Alcohol",
    category: "medical",
    rarity: "common",
    trait1: "Liquid",
    trait2: "Toxicity",
    sources: ["shop", "craft"],
    description: "Frontier moonshine. Disinfects wounds. Also disinfects your will to live.",
  },
  stimulant_tonic: {
    id: "stimulant_tonic",
    name: "Stimulant Tonic",
    category: "medical",
    rarity: "uncommon",
    trait1: "Liquid",
    trait2: "Magic",
    sources: ["craft"],
    description: "Bitter green liquid. Temporarily sharpens reflexes. Withdrawal hits like a cart.",
  },
  blood_vial: {
    id: "blood_vial",
    name: "Blood Vial",
    category: "medical",
    rarity: "rare",
    trait1: "Organic",
    trait2: "Liquid",
    sources: ["craft", "expedition"],
    description: "Preserved blood treated with essence stabilizer. Emergency transfusion material.",
  },
  anti_grey_serum: {
    id: "anti_grey_serum",
    name: "Anti-Grey Serum",
    category: "medical",
    rarity: "legendary",
    trait1: "Magic",
    trait2: "Liquid",
    sources: ["craft"],
    description: "Reverses early-stage Greying. The recipe is worth more than most settlements.",
  },
  iron_ingot: {
    id: "iron_ingot",
    name: "Iron Ingot",
    category: "component",
    rarity: "uncommon",
    trait1: "Density",
    trait2: "Sharpness",
    sources: ["craft"],
    description: "Smelted iron bar. The building block of civilization's sharp edges.",
  },
  copper_ingot: {
    id: "copper_ingot",
    name: "Copper Ingot",
    category: "component",
    rarity: "common",
    trait1: "Density",
    trait2: "None",
    sources: ["craft"],
    description: "Refined copper bar. Conducts essence moderately. Used in wiring and coinage.",
  },
  silver_ingot: {
    id: "silver_ingot",
    name: "Silver Ingot",
    category: "component",
    rarity: "uncommon",
    trait1: "Density",
    trait2: "Magic",
    sources: ["craft"],
    description: "Refined silver bar. Clean, bright, and annoyingly valuable.",
  },
  steel_alloy: {
    id: "steel_alloy",
    name: "Steel Alloy",
    category: "component",
    rarity: "rare",
    trait1: "Density",
    trait2: "Sharpness",
    sources: ["craft"],
    description: "Iron-carbon composite forged at extreme heat. Harder than iron. Holds an edge.",
  },
  leather_strip: {
    id: "leather_strip",
    name: "Leather Strip",
    category: "component",
    rarity: "common",
    trait1: "Organic",
    trait2: "Density",
    sources: ["craft"],
    description:
      "Tanned hide cut into workable strips. Used in everything from armor to book bindings.",
  },
  rope: {
    id: "rope",
    name: "Rope",
    category: "component",
    rarity: "common",
    trait1: "Organic",
    trait2: "None",
    sources: ["craft", "shop"],
    description: "Braided plant fiber. Holds weight, binds cargo, occasionally saves lives.",
  },
  nails: {
    id: "nails",
    name: "Iron Nails",
    category: "component",
    rarity: "common",
    trait1: "Sharpness",
    trait2: "Density",
    sources: ["craft"],
    description:
      "Small pointed fasteners. A pocket of these is worth more than a sword in a frontier camp.",
  },
  glass_vial: {
    id: "glass_vial",
    name: "Glass Vial",
    category: "component",
    rarity: "common",
    trait1: "Density",
    trait2: "None",
    sources: ["craft", "shop"],
    description: "Small sealed container. Holds liquids, powders, and things better left sealed.",
  },
  wax: {
    id: "wax",
    name: "Sealing Wax",
    category: "component",
    rarity: "common",
    trait1: "Organic",
    trait2: "Liquid",
    sources: ["craft"],
    description: "Beeswax and resin blend. Waterproofs, seals, and preserves.",
  },
  cloth: {
    id: "cloth",
    name: "Woven Cloth",
    category: "component",
    rarity: "common",
    trait1: "Organic",
    trait2: "None",
    sources: ["craft", "shop"],
    description: "Rough-spun fabric. Not comfortable. Functional.",
  },
  thread: {
    id: "thread",
    name: "Thread",
    category: "component",
    rarity: "common",
    trait1: "Organic",
    trait2: "None",
    sources: ["craft", "shop"],
    description: "Spun plant fiber or animal sinew. Holds the world together, literally.",
  },
  oil: {
    id: "oil",
    name: "Lamp Oil",
    category: "component",
    rarity: "common",
    trait1: "Liquid",
    trait2: "Organic",
    sources: ["craft", "shop"],
    description: "Rendered from animal fat or pressed from seeds. Burns. That's the point.",
  },
  essence_infused_ingot: {
    id: "essence_infused_ingot",
    name: "Essence-Infused Ingot",
    category: "component",
    rarity: "rare",
    trait1: "Density",
    trait2: "Magic",
    sources: ["craft"],
    description: "Metal bar saturated with stabilized essence. Glows faintly. Warm to the touch.",
  },
  pickaxe: {
    id: "pickaxe",
    name: "Iron Pickaxe",
    category: "tool",
    rarity: "common",
    trait1: "Sharpness",
    trait2: "Density",
    sources: ["craft", "shop"],
    description: "Standard mining tool. Breaks rock. Eventually breaks itself.",
  },
  hatchet: {
    id: "hatchet",
    name: "Hatchet",
    category: "tool",
    rarity: "common",
    trait1: "Sharpness",
    trait2: "Organic",
    sources: ["craft", "shop"],
    description: "Small axe for timber work. Also adequate for self-defense in a pinch.",
  },
  hunting_knife: {
    id: "hunting_knife",
    name: "Hunting Knife",
    category: "tool",
    rarity: "common",
    trait1: "Sharpness",
    trait2: "None",
    sources: ["craft", "shop"],
    description:
      "Fixed-blade utility knife. Skins game, cuts rope, opens cans. Every drifter carries one.",
  },
  lockpick: {
    id: "lockpick",
    name: "Lockpick Set",
    category: "tool",
    rarity: "uncommon",
    trait1: "Sharpness",
    trait2: "None",
    sources: ["craft"],
    description: "Thin metal tools of questionable legality. The Garrison frowns on these.",
  },
  compass: {
    id: "compass",
    name: "Compass",
    category: "tool",
    rarity: "uncommon",
    trait1: "Magic",
    trait2: "Density",
    sources: ["craft", "shop"],
    description: "Magnetized needle in a brass housing. Points north. Usually.",
  },
  lantern: {
    id: "lantern",
    name: "Oil Lantern",
    category: "tool",
    rarity: "common",
    trait1: "Density",
    trait2: "None",
    sources: ["craft", "shop"],
    description:
      "Tin and glass. Burns oil. The difference between seeing danger and walking into it.",
  },
  flint_and_steel: {
    id: "flint_and_steel",
    name: "Flint & Steel",
    category: "tool",
    rarity: "common",
    trait1: "Sharpness",
    trait2: "Density",
    sources: ["craft", "shop"],
    description: "Fire starter. The most basic survival tool. Lose this and you're in trouble.",
  },
  sewing_kit: {
    id: "sewing_kit",
    name: "Sewing Kit",
    category: "tool",
    rarity: "common",
    trait1: "Sharpness",
    trait2: "Organic",
    sources: ["craft", "shop"],
    description: "Needles, thread, and a thimble. Repairs clothing and armor. Saves coin.",
  },
  iron_sword: {
    id: "iron_sword",
    name: "Iron Sword",
    category: "weapon",
    rarity: "uncommon",
    trait1: "Sharpness",
    trait2: "Density",
    sources: ["craft", "shop"],
    description: "Standard-issue Garrison blade. Nothing fancy. Gets the job done.",
  },
  copper_dagger: {
    id: "copper_dagger",
    name: "Copper Dagger",
    category: "weapon",
    rarity: "common",
    trait1: "Sharpness",
    trait2: "None",
    sources: ["craft", "shop"],
    description: "Cheap, soft-metal blade. Better than bare hands. Not by much.",
  },
  wooden_club: {
    id: "wooden_club",
    name: "Wooden Club",
    category: "weapon",
    rarity: "common",
    trait1: "Density",
    trait2: "Organic",
    sources: ["craft"],
    description: "A heavy piece of oak shaped for hitting things. Elegance is not the point.",
  },
  longbow: {
    id: "longbow",
    name: "Longbow",
    category: "weapon",
    rarity: "uncommon",
    trait1: "Organic",
    trait2: "Sharpness",
    sources: ["craft"],
    description:
      "Spruce-stave bow. Effective at range. Less effective when something is already biting you.",
  },
  spear: {
    id: "spear",
    name: "Spear",
    category: "weapon",
    rarity: "common",
    trait1: "Sharpness",
    trait2: "Organic",
    sources: ["craft"],
    description:
      "Pointed stick, refined. Keeps danger at arm's length. The oldest weapon for a reason.",
  },
  war_hammer: {
    id: "war_hammer",
    name: "War Hammer",
    category: "weapon",
    rarity: "uncommon",
    trait1: "Density",
    trait2: "Sharpness",
    sources: ["craft"],
    description: "Heavy iron head on an oak shaft. Ignores armor. Shatters bone.",
  },
  crossbow: {
    id: "crossbow",
    name: "Crossbow",
    category: "weapon",
    rarity: "rare",
    trait1: "Sharpness",
    trait2: "Density",
    sources: ["craft"],
    description:
      "Mechanical bow with a locking mechanism. Requires bolts. Punches through hide armor.",
  },
  serrated_blade: {
    id: "serrated_blade",
    name: "Serrated Blade",
    category: "weapon",
    rarity: "rare",
    trait1: "Sharpness",
    trait2: "Toxicity",
    sources: ["craft"],
    description:
      "Jagged-edged knife designed to cause wounds that don't close. Cruel but effective.",
  },
  leather_vest: {
    id: "leather_vest",
    name: "Leather Vest",
    category: "armor",
    rarity: "common",
    trait1: "Organic",
    trait2: "Density",
    sources: ["craft", "shop"],
    description: "Boiled leather chest piece. Stops a glancing blow. Don't expect miracles.",
  },
  iron_helmet: {
    id: "iron_helmet",
    name: "Iron Helmet",
    category: "armor",
    rarity: "uncommon",
    trait1: "Density",
    trait2: "Sharpness",
    sources: ["craft"],
    description: "Open-face iron helm. Protects the skull. Limits peripheral vision.",
  },
  chainmail: {
    id: "chainmail",
    name: "Chainmail Shirt",
    category: "armor",
    rarity: "rare",
    trait1: "Density",
    trait2: "Sharpness",
    sources: ["craft"],
    description: "Interlocking iron rings sewn onto leather backing. Heavy. Effective. Expensive.",
  },
  wooden_shield: {
    id: "wooden_shield",
    name: "Wooden Shield",
    category: "armor",
    rarity: "common",
    trait1: "Density",
    trait2: "Organic",
    sources: ["craft"],
    description: "Ironwood-bound oak shield. Absorbs impacts. Splinters eventually replace it.",
  },
  fur_cloak: {
    id: "fur_cloak",
    name: "Fur Cloak",
    category: "armor",
    rarity: "uncommon",
    trait1: "Organic",
    trait2: "Density",
    sources: ["craft"],
    description: "Wolf pelt outer layer with cloth lining. Warmth and minor essence shielding.",
  },
  iron_greaves: {
    id: "iron_greaves",
    name: "Iron Greaves",
    category: "armor",
    rarity: "uncommon",
    trait1: "Density",
    trait2: "None",
    sources: ["craft"],
    description: "Shin guards. Protect the legs. Make you louder when walking. Trade-offs.",
  },
  sharp_stone: {
    id: "sharp_stone",
    name: "Sharp Stone",
    category: "mineral",
    rarity: "common",
    trait1: "Sharpness",
    trait2: "Density",
    sources: ["craft"],
    description: "A stone shattered into jagged edges. Crude, but dangerous.",
  },
  crushed_copper: {
    id: "crushed_copper",
    name: "Crushed Copper",
    category: "mineral",
    rarity: "common",
    trait1: "Density",
    trait2: "Liquid",
    sources: ["craft"],
    description: "Copper ore reduced to fine granules. Ready for smelting or alchemical solution.",
  },
  iron_shards: {
    id: "iron_shards",
    name: "Iron Shards",
    category: "mineral",
    rarity: "uncommon",
    trait1: "Sharpness",
    trait2: "Density",
    sources: ["craft"],
    description: "Fragments of deep-vein iron. Their edges hum with residual essence.",
  },
  tin_dust: {
    id: "tin_dust",
    name: "Tin Dust",
    category: "mineral",
    rarity: "common",
    trait1: "Density",
    trait2: "None",
    sources: ["craft"],
    description: "Fine grey dust. Essential for low-temperature alloys.",
  },
  silver_dust: {
    id: "silver_dust",
    name: "Silver Dust",
    category: "mineral",
    rarity: "uncommon",
    trait1: "Magic",
    trait2: "Density",
    sources: ["craft"],
    description: "Shimmering powder that conducts essence with high efficiency.",
  },
  coal_dust: {
    id: "coal_dust",
    name: "Coal Dust",
    category: "mineral",
    rarity: "common",
    trait1: "Toxicity",
    trait2: "Density",
    sources: ["craft"],
    description: "Highly flammable and filthy. Useful in concentrated amounts.",
  },
  sulfur_powder: {
    id: "sulfur_powder",
    name: "Sulfur Powder",
    category: "mineral",
    rarity: "uncommon",
    trait1: "Toxicity",
    trait2: "None",
    sources: ["craft"],
    description: "Refined yellow powder. The primary catalyst for chemical violence.",
  },
  quartz_dust: {
    id: "quartz_dust",
    name: "Quartz Dust",
    category: "mineral",
    rarity: "uncommon",
    trait1: "Magic",
    trait2: "None",
    sources: ["craft"],
    description: "Refractive crystal dust. Used to stabilize magical structures.",
  },
  obsidian_blade: {
    id: "obsidian_blade",
    name: "Obsidian Blade",
    category: "mineral",
    rarity: "rare",
    trait1: "Sharpness",
    trait2: "Magic",
    sources: ["craft"],
    description: "A volcanic glass shard shaped into a lethal edge. It drinks light.",
  },
  crushed_ruby: {
    id: "crushed_ruby",
    name: "Crushed Ruby",
    category: "mineral",
    rarity: "rare",
    trait1: "Magic",
    trait2: "Density",
    sources: ["craft"],
    description: "Crimson dust that radiates a constant, low-level warmth.",
  },
  crushed_sapphire: {
    id: "crushed_sapphire",
    name: "Crushed Sapphire",
    category: "mineral",
    rarity: "rare",
    trait1: "Magic",
    trait2: "Liquid",
    sources: ["craft"],
    description: "Aqueous blue powder that seems to ripple when moved.",
  },
  essence_shards: {
    id: "essence_shards",
    name: "Essence Shards",
    category: "mineral",
    rarity: "legendary",
    trait1: "Magic",
    trait2: "Magic",
    sources: ["craft"],
    description: "Fragments of pure crystallized essence. Each shard is a potential catastrophe.",
  },
  oak_plank: {
    id: "oak_plank",
    name: "Oak Plank",
    category: "timber",
    rarity: "common",
    trait1: "Organic",
    trait2: "Density",
    sources: ["craft"],
    description: "Durable board of seasoned oak. The backbone of construction.",
  },
  spruce_plank: {
    id: "spruce_plank",
    name: "Spruce Plank",
    category: "timber",
    rarity: "common",
    trait1: "Organic",
    trait2: "None",
    sources: ["craft"],
    description: "Light, easy-to-work board. Good for detail work and crates.",
  },
  palm_plank: {
    id: "palm_plank",
    name: "Palm Plank",
    category: "timber",
    rarity: "uncommon",
    trait1: "Organic",
    trait2: "Liquid",
    sources: ["craft"],
    description: "Wide palm board that keeps a little sea damp in its grain.",
  },
  palm_strips: {
    id: "palm_strips",
    name: "Palm Strips",
    category: "timber",
    rarity: "uncommon",
    trait1: "Organic",
    trait2: "Liquid",
    sources: ["craft"],
    description: "Flexible, oily strips of palm wood. Excellent for weaving.",
  },
  pine_plank: {
    id: "pine_plank",
    name: "Pine Plank",
    category: "timber",
    rarity: "uncommon",
    trait1: "Organic",
    trait2: "Toxicity",
    sources: ["craft"],
    description: "Resinous board that resists moisture and rot.",
  },
  ironwood_plank: {
    id: "ironwood_plank",
    name: "Ironwood Plank",
    category: "timber",
    rarity: "rare",
    trait1: "Organic",
    trait2: "Density",
    sources: ["craft"],
    description: "A board heavy as lead and hard as stone. Requires special tools to cut.",
  },
  charcoal_powder: {
    id: "charcoal_powder",
    name: "Charcoal Powder",
    category: "timber",
    rarity: "common",
    trait1: "Density",
    trait2: "Toxicity",
    sources: ["craft"],
    description: "Purified carbon dust. Highly absorbent and useful in filtration.",
  },
  thick_resin: {
    id: "thick_resin",
    name: "Thick Resin",
    category: "timber",
    rarity: "common",
    trait1: "Organic",
    trait2: "Liquid",
    sources: ["craft"],
    description: "Sap boiled down into a potent, slow-setting adhesive.",
  },
  fungal_spores: {
    id: "fungal_spores",
    name: "Fungal Spores",
    category: "timber",
    rarity: "common",
    trait1: "Organic",
    trait2: "Toxicity",
    sources: ["craft"],
    description: "Fine, irritating dust collected from rotted timber. Potentially bio-hazardous.",
  },
  crushed_red_herb: {
    id: "crushed_red_herb",
    name: "Crushed Red Herb",
    category: "herb",
    rarity: "uncommon",
    trait1: "Organic",
    trait2: "Magic",
    sources: ["craft"],
    description: "Bruised herb leaves, releasing concentrated healing essence.",
  },
  moss_extract: {
    id: "moss_extract",
    name: "Moss Extract",
    category: "herb",
    rarity: "uncommon",
    trait1: "Organic",
    trait2: "Liquid",
    sources: ["craft"],
    description: "A luminous, thick liquid distilled from blue cave moss.",
  },
  nightshade_ooze: {
    id: "nightshade_ooze",
    name: "Nightshade Ooze",
    category: "herb",
    rarity: "rare",
    trait1: "Organic",
    trait2: "Toxicity",
    sources: ["craft"],
    description: "A dark, syrupy concentrate of lethal nightshade berries.",
  },
  mushroom_paste: {
    id: "mushroom_paste",
    name: "Mushroom Paste",
    category: "herb",
    rarity: "uncommon",
    trait1: "Magic",
    trait2: "Organic",
    sources: ["craft"],
    description: "A glowing pulp of glowcap mushrooms. Humid and faintly vibrating.",
  },
  thorn_point: {
    id: "thorn_point",
    name: "Thorn Point",
    category: "herb",
    rarity: "common",
    trait1: "Sharpness",
    trait2: "None",
    sources: ["craft"],
    description: "A single, essence-hardened thorn removed from a vine.",
  },
  shredded_tobacco: {
    id: "shredded_tobacco",
    name: "Shredded Tobacco",
    category: "herb",
    rarity: "common",
    trait1: "Organic",
    trait2: "Toxicity",
    sources: ["craft"],
    description: "Dried tobacco leaves cut for smoking or medicinal poultices.",
  },
  lily_extract: {
    id: "lily_extract",
    name: "Lily Extract",
    category: "herb",
    rarity: "rare",
    trait1: "Magic",
    trait2: "Liquid",
    sources: ["craft"],
    description: "A clear, ethereal liquid that smells of cold metal and white flowers.",
  },
  swamp_pulp: {
    id: "swamp_pulp",
    name: "Swamp Pulp",
    category: "herb",
    rarity: "uncommon",
    trait1: "Organic",
    trait2: "Toxicity",
    sources: ["craft"],
    description: "Fibrous swamp root mashed into a bitter, cleansing paste.",
  },
  lavender_oil: {
    id: "lavender_oil",
    name: "Lavender Oil",
    category: "herb",
    rarity: "common",
    trait1: "Organic",
    trait2: "Liquid",
    sources: ["craft"],
    description: "Sweet-smelling oil used for calming and masking decay.",
  },
  bark_pulp: {
    id: "bark_pulp",
    name: "Bark Pulp",
    category: "herb",
    rarity: "common",
    trait1: "Organic",
    trait2: "None",
    sources: ["craft"],
    description: "Macerated inner bark. Used for tea or as a base for salves.",
  },
  witchgrass_extract: {
    id: "witchgrass_extract",
    name: "Witchgrass Extract",
    category: "herb",
    rarity: "uncommon",
    trait1: "Magic",
    trait2: "Toxicity",
    sources: ["craft"],
    description: "Black liquid that seems to pull slightly towards essence-rich areas.",
  },
  corpse_essence: {
    id: "corpse_essence",
    name: "Corpse Essence",
    category: "herb",
    rarity: "rare",
    trait1: "Toxicity",
    trait2: "Magic",
    sources: ["craft"],
    description: "A concentrated oil that carries the heavy scent of death and magic.",
  },
  ground_tooth: {
    id: "ground_tooth",
    name: "Ground Wolf Tooth",
    category: "animal",
    rarity: "uncommon",
    trait1: "Sharpness",
    trait2: "None",
    sources: ["craft"],
    description: "A sharp, abrasive powder made from crystalline predator teeth.",
  },
  fur_scraps: {
    id: "fur_scraps",
    name: "Fur Scraps",
    category: "animal",
    rarity: "uncommon",
    trait1: "Organic",
    trait2: "Density",
    sources: ["craft"],
    description: "Sections of wolf pelt prepared for lining or insulation.",
  },
  tusk_shards: {
    id: "tusk_shards",
    name: "Tusk Shards",
    category: "animal",
    rarity: "uncommon",
    trait1: "Sharpness",
    trait2: "Density",
    sources: ["craft"],
    description: "Splinters of boar tusk. Extremely hard and resistant to heat.",
  },
  leather_scraps: {
    id: "leather_scraps",
    name: "Leather Scraps",
    category: "animal",
    rarity: "uncommon",
    trait1: "Density",
    trait2: "Organic",
    sources: ["craft"],
    description: "Trimmings of boar hide, too small for large garments but useful for repairs.",
  },
  wing_powder: {
    id: "wing_powder",
    name: "Wing Powder",
    category: "animal",
    rarity: "rare",
    trait1: "Magic",
    trait2: "Organic",
    sources: ["craft"],
    description:
      "Iridescent dust collected from Veilmoth wings. Flickers out of existence briefly.",
  },
  lurker_venom: {
    id: "lurker_venom",
    name: "Lurker Venom",
    category: "animal",
    rarity: "rare",
    trait1: "Sharpness",
    trait2: "Toxicity",
    sources: ["craft"],
    description: "Numbing liquid extracted from Cave Lurker claws.",
  },
  rat_sinew: {
    id: "rat_sinew",
    name: "Rat Sinew",
    category: "animal",
    rarity: "common",
    trait1: "Organic",
    trait2: "None",
    sources: ["craft"],
    description: "Short, thin strands of tendon from tunnel rats.",
  },
  feather_quill: {
    id: "feather_quill",
    name: "Feather Quill",
    category: "animal",
    rarity: "common",
    trait1: "Organic",
    trait2: "Sharpness",
    sources: ["craft"],
    description: "A crow feather stripped of its barbs, leaving only the hard quill.",
  },
  venom_extract: {
    id: "venom_extract",
    name: "Venom Extract",
    category: "animal",
    rarity: "rare",
    trait1: "Toxicity",
    trait2: "Liquid",
    sources: ["craft"],
    description: "Concentrated snake venom. Lethal in even minute quantities.",
  },
  bone_dust: {
    id: "bone_dust",
    name: "Bone Dust",
    category: "animal",
    rarity: "common",
    trait1: "Density",
    trait2: "None",
    sources: ["craft"],
    description: "Finely ground bone. Used as a binder or alchemical substrate.",
  },
  cured_sinew: {
    id: "cured_sinew",
    name: "Cured Sinew",
    category: "animal",
    rarity: "common",
    trait1: "Organic",
    trait2: "Density",
    sources: ["craft"],
    description: "Animal sinew treated and stretched into a high-tensile cord.",
  },
  purified_fat: {
    id: "purified_fat",
    name: "Purified Fat",
    category: "animal",
    rarity: "common",
    trait1: "Organic",
    trait2: "Liquid",
    sources: ["craft"],
    description: "Rendered animal fat, cleared of impurities and odors.",
  },
  silk_thread: {
    id: "silk_thread",
    name: "Silk Thread",
    category: "animal",
    rarity: "rare",
    trait1: "Organic",
    trait2: "Magic",
    sources: ["craft"],
    description: "Spider silk spun into a thread that can carry a magical charge.",
  },
  demon_ichor: {
    id: "demon_ichor",
    name: "Demon Ichor",
    category: "animal",
    rarity: "legendary",
    trait1: "Toxicity",
    trait2: "Liquid",
    sources: ["craft"],
    description: "Pure, undiluted black blood from the deeps. It seems to watch you.",
  },
  ash_concentrate: {
    id: "ash_concentrate",
    name: "Ash Concentrate",
    category: "reagent",
    rarity: "common",
    trait1: "None",
    trait2: "None",
    sources: ["craft"],
    description: "Volatile ash refined into a stable alchemical base. Still mostly useless.",
  },
  essence_slurry: {
    id: "essence_slurry",
    name: "Essence Slurry",
    category: "reagent",
    rarity: "uncommon",
    trait1: "Magic",
    trait2: "Liquid",
    sources: ["craft"],
    description: "Essence dust suspended in distilled water. Highly reactive.",
  },
  stabilized_salt: {
    id: "stabilized_salt",
    name: "Stabilized Salt",
    category: "reagent",
    rarity: "uncommon",
    trait1: "Density",
    trait2: "Magic",
    sources: ["craft"],
    description: "Grey salt treated with essence dust to enhance its stabilizing properties.",
  },
  unstable_powder: {
    id: "unstable_powder",
    name: "Unstable Powder",
    category: "reagent",
    rarity: "uncommon",
    trait1: "Toxicity",
    trait2: "Magic",
    sources: ["craft"],
    description: "A precursor to black powder, lacking its explosive force but highly volatile.",
  },
  purified_quicksilver: {
    id: "purified_quicksilver",
    name: "Purified Quicksilver",
    category: "reagent",
    rarity: "rare",
    trait1: "Liquid",
    trait2: "Magic",
    sources: ["craft"],
    description:
      "Mercury from which the most deadly toxins have been removed, leaving pure conductant.",
  },
  tallow_block: {
    id: "tallow_block",
    name: "Tallow Block",
    category: "reagent",
    rarity: "common",
    trait1: "Organic",
    trait2: "Density",
    sources: ["craft"],
    description: "Rendered fat cast into a solid block for easy transport and storage.",
  },
  phosphite_sludge: {
    id: "phosphite_sludge",
    name: "Phosphite Sludge",
    category: "reagent",
    rarity: "uncommon",
    trait1: "Toxicity",
    trait2: "Liquid",
    sources: ["craft"],
    description: "A glowing, caustic mud-like substance that burns to the touch.",
  },
  infused_water: {
    id: "infused_water",
    name: "Infused Water",
    category: "reagent",
    rarity: "uncommon",
    trait1: "Liquid",
    trait2: "Magic",
    sources: ["craft"],
    description: "Distilled water that has absorbed residual essence from nearby crystals.",
  },
  concentrated_acid: {
    id: "concentrated_acid",
    name: "Concentrated Acid",
    category: "reagent",
    rarity: "rare",
    trait1: "Toxicity",
    trait2: "Density",
    sources: ["craft"],
    description: "Acid vial content refined into a much more stable and powerful corrosive.",
  },
  sticky_binding_agent: {
    id: "sticky_binding_agent",
    name: "Sticky Binding Agent",
    category: "reagent",
    rarity: "uncommon",
    trait1: "Density",
    trait2: "Liquid",
    sources: ["craft"],
    description: "Binding agent reinforced with wood resin for maximum adherence.",
  },
  medical_cloth: {
    id: "medical_cloth",
    name: "Medical Cloth",
    category: "medical",
    rarity: "common",
    trait1: "Organic",
    trait2: "None",
    sources: ["craft"],
    description: "Bandages treated with mild disinfectants.",
  },
  salve_base: {
    id: "salve_base",
    name: "Salve Base",
    category: "medical",
    rarity: "uncommon",
    trait1: "Liquid",
    trait2: "Organic",
    sources: ["craft"],
    description: "A neutral ointment prepared to receive active herbal ingredients.",
  },
  antitoxin_base: {
    id: "antitoxin_base",
    name: "Antitoxin Base",
    category: "medical",
    rarity: "uncommon",
    trait1: "Toxicity",
    trait2: "Organic",
    sources: ["craft"],
    description: "A compound designed to absorb and neutralize common toxins.",
  },
  ward_fragment: {
    id: "ward_fragment",
    name: "Ward Fragment",
    category: "medical",
    rarity: "rare",
    trait1: "Magic",
    trait2: "None",
    sources: ["craft"],
    description: "A shard of an essence ward, still containing faint protective energy.",
  },
  packed_ration: {
    id: "packed_ration",
    name: "Packed Ration",
    category: "medical",
    rarity: "common",
    trait1: "Organic",
    trait2: "Density",
    sources: ["craft"],
    description: "Rations compressed and sealed for maximum shelf life.",
  },
  purified_liquid: {
    id: "purified_liquid",
    name: "Purified Liquid",
    category: "medical",
    rarity: "common",
    trait1: "Liquid",
    trait2: "None",
    sources: ["craft"],
    description: "Water that has undergone triple-distillation to ensure zero essence taint.",
  },
  potent_spirit: {
    id: "potent_spirit",
    name: "Potent Spirit",
    category: "medical",
    rarity: "common",
    trait1: "Liquid",
    trait2: "Toxicity",
    sources: ["craft"],
    description: "Alcohol distilled to the threshold of palatability.",
  },
  stimulant_base: {
    id: "stimulant_base",
    name: "Stimulant Base",
    category: "medical",
    rarity: "uncommon",
    trait1: "Magic",
    trait2: "Liquid",
    sources: ["craft"],
    description: "An aqueous solution primed for stimulant herbs.",
  },
  transfusable_blood: {
    id: "transfusable_blood",
    name: "Transfusable Blood",
    category: "medical",
    rarity: "rare",
    trait1: "Organic",
    trait2: "Liquid",
    sources: ["craft"],
    description: "Stabilized blood ready for immediate use in medical procedures.",
  },
  serum_component: {
    id: "serum_component",
    name: "Serum Component",
    category: "medical",
    rarity: "legendary",
    trait1: "Magic",
    trait2: "Liquid",
    sources: ["craft"],
    description: "One of the complex ingredients required for the anti-grey serum.",
  },
  iron_filings: {
    id: "iron_filings",
    name: "Iron Filings",
    category: "component",
    rarity: "uncommon",
    trait1: "Density",
    trait2: "Sharpness",
    sources: ["craft"],
    description: "Fine shavings of iron. Useful for magnetic and alchemical experiments.",
  },
  copper_filings: {
    id: "copper_filings",
    name: "Copper Filings",
    category: "component",
    rarity: "common",
    trait1: "Density",
    trait2: "None",
    sources: ["craft"],
    description: "Small shavings of copper ore. Conducts essence well in powder form.",
  },
  steel_shards: {
    id: "steel_shards",
    name: "Steel Shards",
    category: "component",
    rarity: "rare",
    trait1: "Density",
    trait2: "Sharpness",
    sources: ["craft"],
    description: "Fragments of high-grade steel. Retain their edge even when broken.",
  },
  tanned_hide: {
    id: "tanned_hide",
    name: "Tanned Hide",
    category: "component",
    rarity: "common",
    trait1: "Organic",
    trait2: "Density",
    sources: ["craft"],
    description: "Animal hide that has been cleaned and treated, ready for cutting.",
  },
  hemp_fiber: {
    id: "hemp_fiber",
    name: "Hemp Fiber",
    category: "component",
    rarity: "common",
    trait1: "Organic",
    trait2: "None",
    sources: ["craft"],
    description: "Plant fibers stripped and prepared for spinning into rope or cloth.",
  },
  iron_pins: {
    id: "iron_pins",
    name: "Iron Pins",
    category: "component",
    rarity: "common",
    trait1: "Sharpness",
    trait2: "Density",
    sources: ["craft"],
    description: "Tiny, sharp iron fasteners. Useful for delicate mechanical work.",
  },
  glass_shards: {
    id: "glass_shards",
    name: "Glass Shards",
    category: "component",
    rarity: "common",
    trait1: "Density",
    trait2: "Sharpness",
    sources: ["craft"],
    description: "Broken glass. Dangerous to handle, but useful for optics or as a cheap abrasive.",
  },
  processed_wax: {
    id: "processed_wax",
    name: "Processed Wax",
    category: "component",
    rarity: "common",
    trait1: "Organic",
    trait2: "None",
    sources: ["craft"],
    description: "Wax that has been melted and cleared of impurities.",
  },
  raw_fabric: {
    id: "raw_fabric",
    name: "Raw Fabric",
    category: "component",
    rarity: "common",
    trait1: "Organic",
    trait2: "None",
    sources: ["craft"],
    description: "Bolts of uncolored, rough-woven material.",
  },
  loose_thread: {
    id: "loose_thread",
    name: "Loose Thread",
    category: "component",
    rarity: "common",
    trait1: "Organic",
    trait2: "None",
    sources: ["craft"],
    description: "Small spools of thread for minor repairs.",
  },
  heavy_oil: {
    id: "heavy_oil",
    name: "Heavy Oil",
    category: "component",
    rarity: "common",
    trait1: "Liquid",
    trait2: "Organic",
    sources: ["craft"],
    description: "Oils that have been thickened for use in industrial lighting or lubrication.",
  },
  magic_dust: {
    id: "magic_dust",
    name: "Magic Dust",
    category: "component",
    rarity: "rare",
    trait1: "Magic",
    trait2: "None",
    sources: ["craft"],
    description: "Concentrated essence particles extracted from infused materials.",
  },
  broken_pickaxe: {
    id: "broken_pickaxe",
    name: "Broken Pickaxe",
    category: "tool",
    rarity: "common",
    trait1: "Density",
    trait2: "None",
    sources: ["craft"],
    description: "A snap in the handle or a crack in the head has rendered this tool useless.",
  },
  broken_hatchet: {
    id: "broken_hatchet",
    name: "Broken Hatchet",
    category: "tool",
    rarity: "common",
    trait1: "Organic",
    trait2: "None",
    sources: ["craft"],
    description: "The blade is chipped beyond use or the handle has splintered.",
  },
  dull_knife: {
    id: "dull_knife",
    name: "Dull Knife",
    category: "tool",
    rarity: "common",
    trait1: "Sharpness",
    trait2: "None",
    sources: ["craft"],
    description: "The edge is gone. It can barely cut bread, let alone leather.",
  },
  bent_lockpick: {
    id: "bent_lockpick",
    name: "Bent Lockpick",
    category: "tool",
    rarity: "uncommon",
    trait1: "Sharpness",
    trait2: "None",
    sources: ["craft"],
    description: "A failed attempt has warped the metal. It's useless for picking now.",
  },
  shattered_compass: {
    id: "shattered_compass",
    name: "Shattered Compass",
    category: "tool",
    rarity: "uncommon",
    trait1: "Magic",
    trait2: "None",
    sources: ["craft"],
    description: "The glass is broken and the needle is stuck. It points nowhere.",
  },
  smashed_lantern: {
    id: "smashed_lantern",
    name: "Smashed Lantern",
    category: "tool",
    rarity: "common",
    trait1: "Density",
    trait2: "None",
    sources: ["craft"],
    description: "Cracked glass and a leaking fuel tank. A fire hazard, nothing more.",
  },
  dull_flint: {
    id: "dull_flint",
    name: "Dull Flint",
    category: "tool",
    rarity: "common",
    trait1: "Sharpness",
    trait2: "None",
    sources: ["craft"],
    description: "The sparking edge has been worn smooth. It won't start a fire.",
  },
  broken_needle: {
    id: "broken_needle",
    name: "Broken Needle",
    category: "tool",
    rarity: "common",
    trait1: "Sharpness",
    trait2: "None",
    sources: ["craft"],
    description: "The eye has snapped or the point has blunted.",
  },
  notched_sword: {
    id: "notched_sword",
    name: "Notched Sword",
    category: "weapon",
    rarity: "uncommon",
    trait1: "Sharpness",
    trait2: "None",
    sources: ["craft"],
    description: "Impacts have left the edge jagged and unreliable.",
  },
  chipped_dagger: {
    id: "chipped_dagger",
    name: "Chipped Dagger",
    category: "weapon",
    rarity: "common",
    trait1: "Sharpness",
    trait2: "None",
    sources: ["craft"],
    description: "A small piece of the blade is missing near the tip.",
  },
  splintered_club: {
    id: "splintered_club",
    name: "Splintered Club",
    category: "weapon",
    rarity: "common",
    trait1: "Density",
    trait2: "None",
    sources: ["craft"],
    description: "The wood is fraying. One more hard hit and it will fall apart.",
  },
  snapped_bow: {
    id: "snapped_bow",
    name: "Snapped Bow",
    category: "weapon",
    rarity: "uncommon",
    trait1: "Organic",
    trait2: "None",
    sources: ["craft"],
    description: "The stave has fractured under tension.",
  },
  broken_spear: {
    id: "broken_spear",
    name: "Broken Spear",
    category: "weapon",
    rarity: "common",
    trait1: "Sharpness",
    trait2: "None",
    sources: ["craft"],
    description: "The shaft is snapped or the head has come loose.",
  },
  cracked_hammer: {
    id: "cracked_hammer",
    name: "Cracked Hammer",
    category: "weapon",
    rarity: "uncommon",
    trait1: "Density",
    trait2: "None",
    sources: ["craft"],
    description: "A stress fracture through the iron head makes it dangerous to swing.",
  },
  broken_crossbow: {
    id: "broken_crossbow",
    name: "Broken Crossbow",
    category: "weapon",
    rarity: "rare",
    trait1: "Sharpness",
    trait2: "None",
    sources: ["craft"],
    description: "The trigger mechanism or the limbs have failed.",
  },
  dull_serrated_blade: {
    id: "dull_serrated_blade",
    name: "Dull Serrated Blade",
    category: "weapon",
    rarity: "rare",
    trait1: "Sharpness",
    trait2: "None",
    sources: ["craft"],
    description: "The teeth are worn down, losing their ability to tear.",
  },
  torn_leather_vest: {
    id: "torn_leather_vest",
    name: "Torn Leather Vest",
    category: "armor",
    rarity: "common",
    trait1: "Organic",
    trait2: "None",
    sources: ["craft"],
    description: "Rips and punctures have compromised its protective value.",
  },
  dented_iron_helmet: {
    id: "dented_iron_helmet",
    name: "Dented Iron Helmet",
    category: "armor",
    rarity: "uncommon",
    trait1: "Density",
    trait2: "None",
    sources: ["craft"],
    description: "A heavy impact has deformed the metal, making it uncomfortable and weak.",
  },
  rusted_chainmail: {
    id: "rusted_chainmail",
    name: "Rusted Chainmail",
    category: "armor",
    rarity: "rare",
    trait1: "Density",
    trait2: "None",
    sources: ["craft"],
    description: "Neglect and dampness have turned the rings into a crumbling mess.",
  },
  broken_wooden_shield: {
    id: "broken_wooden_shield",
    name: "Broken Wooden Shield",
    category: "armor",
    rarity: "common",
    trait1: "Density",
    trait2: "None",
    sources: ["craft"],
    description: "Split boards and a loose handle.",
  },
  shabby_fur_cloak: {
    id: "shabby_fur_cloak",
    name: "Shabby Fur Cloak",
    category: "armor",
    rarity: "uncommon",
    trait1: "Organic",
    trait2: "None",
    sources: ["craft"],
    description: "Matted fur and holes. It protects from neither cold nor essence.",
  },
  dented_iron_greaves: {
    id: "dented_iron_greaves",
    name: "Dented Iron Greaves",
    category: "armor",
    rarity: "uncommon",
    trait1: "Density",
    trait2: "None",
    sources: ["craft"],
    description: "Bent plates that pinch the legs and offer little protection.",
  },
  essence_vial: {
    id: "essence_vial",
    name: "Essence Vial",
    category: "reagent",
    rarity: "rare",
    trait1: "Magic",
    trait2: "Liquid",
    sources: ["craft"],
    description: "A glass vial pulsing with raw, stabilized essence. Dangerous to open.",
  },
  bronze_ingot: {
    id: "bronze_ingot",
    name: "Bronze Ingot",
    category: "component",
    rarity: "uncommon",
    trait1: "Density",
    trait2: "None",
    sources: ["craft"],
    description: "An alloy of copper and tin. Stronger than copper, easier to work than iron.",
  },
  sharpening_stone: {
    id: "sharpening_stone",
    name: "Sharpening Stone",
    category: "tool",
    rarity: "common",
    trait1: "Sharpness",
    trait2: "Density",
    sources: ["craft", "shop"],
    description: "A hunk of abrasive rock used to keep edges keen.",
  },
  refined_oil: {
    id: "refined_oil",
    name: "Refined Oil",
    category: "component",
    rarity: "uncommon",
    trait1: "Liquid",
    trait2: "Organic",
    sources: ["craft"],
    description: "Clean-burning oil used for high-end lanterns and explosives.",
  },
  mana_paste: {
    id: "mana_paste",
    name: "Mana Paste",
    category: "reagent",
    rarity: "rare",
    trait1: "Magic",
    trait2: "Organic",
    sources: ["craft"],
    description: "A thick, glowing ointment that restores magical circulation.",
  },
});
